services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    networks:
      - internal
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    env_file:
      - .env
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./function_configs:/app/backend/open-webui/function_configs
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
      - "8080:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'BYPASS_MODEL_ACCESS_CONTROL=True'
      - 'PDF_EXTRACT_IMAGES=True'
      - 'ENABLE_SIGNUP=True'
      - 'RAG_EMBEDDING_ENGINE=openai'
      - 'RAG_EMBEDDING_MODEL=bge-m3'
      - 'OPENAI_API_BASE_URLS=${MWS_API_BASE}' # в проде убрать
      - 'OPENAI_API_KEYS=${MWS_API_TOKEN}' # в проде убрать
      # - 'ENV=dev' # в проде убрать
      # Включить веб-поиск
      - 'ENABLE_RAG_WEB_SEARCH=True'
      # Адрес SearXNG (важно: шаблон <query> обязателен!)
      - 'SEARXNG_QUERY_URL=http://searxng_data-searxng:8080/search?q=<query>&format=json' 
      # Количество результатов
      - 'RAG_WEB_SEARCH_RESULT_COUNT=5'
      # Язык поиска
      - 'SEARXNG_LANGUAGE=all'
      # Ограничение одновременных запросов (рекомендуется)
      - 'RAG_WEB_SEARCH_CONCURRENT_REQUESTS=1'
      # Роль по умолчанию - пользватель (без прав адмиина)
      - 'DEFAULT_USER_ROLE=user'
      - 'ENABLE_PERSISTENT_CONFIG=False'
      # Переменные окружения для аудио
      - 'AUDIO_STT_ENGINE=openai'
      - 'AUDIO_STT_MODEL=wisper-turbo-local'
      - 'AUDIO_STT_OPENAI_API_BASE_URL=${MWS_API_BASE}' # в проде убрать
      - 'AUDIO_STT_OPENAI_API_KEY=${MWS_API_TOKEN}' # в проде убрать
      # Форматы файлов
      - 'RAG_ALLOWED_FILE_EXTENSIONS=.pdf,.txt,.md,.docx'

    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - webui-net

volumes:
  ollama: {}
  open-webui: {}

networks:
  webui-net: {}
